### ISSUE TITLE
Any way to size logo based on module units?

### ISSUE THREAD

**Issue by x032205** [Castlenine/svelte-qrcode#3]
First off, I love this project, amazing job on it!

But anyways, I generate QR codes for sending funds to crypto addresses, and every crypto protocol has a different logo and a different address length. This results in some logos looking great, but some cropping out a few "dots". If it was possible to size logos based off of module units, then this problem would not exist.

Here's an example of a logo "cutting off" some of the modules.
<img width="650" alt="image" src="https://github.com/user-attachments/assets/ade02042-e923-4e0f-a7ce-fc9803f63181">

**Comment by x032205** [comment]
I made a PR fixing this issue: https://github.com/Castlenine/svelte-qrcode/pull/5

**Comment by Castlenine** [comment]
Awesome, I'm adding it to the next version
